/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as ApiRecipeImageRouteImport } from './routes/api/recipe-image'
import { Route as RecipesRecipeIdIndexRouteImport } from './routes/recipes/$recipeId/index'
import { Route as AuthMyRecipesIndexRouteImport } from './routes/_auth/my-recipes/index'
import { Route as RecipesRecipeIdEditRouteImport } from './routes/recipes/$recipeId/edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthMyRecipesNewRouteImport } from './routes/_auth/my-recipes/new'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipeImageRoute = ApiRecipeImageRouteImport.update({
  id: '/api/recipe-image',
  path: '/api/recipe-image',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdIndexRoute = RecipesRecipeIdIndexRouteImport.update({
  id: '/recipes/$recipeId/',
  path: '/recipes/$recipeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMyRecipesIndexRoute = AuthMyRecipesIndexRouteImport.update({
  id: '/my-recipes/',
  path: '/my-recipes/',
  getParentRoute: () => AuthRoute,
} as any)
const RecipesRecipeIdEditRoute = RecipesRecipeIdEditRouteImport.update({
  id: '/recipes/$recipeId/edit',
  path: '/recipes/$recipeId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMyRecipesNewRoute = AuthMyRecipesNewRouteImport.update({
  id: '/my-recipes/new',
  path: '/my-recipes/new',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/recipe-image': typeof ApiRecipeImageRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/recipes/': typeof RecipesIndexRoute
  '/my-recipes/new': typeof AuthMyRecipesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/my-recipes/': typeof AuthMyRecipesIndexRoute
  '/recipes/$recipeId/': typeof RecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/recipe-image': typeof ApiRecipeImageRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/recipes': typeof RecipesIndexRoute
  '/my-recipes/new': typeof AuthMyRecipesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/my-recipes': typeof AuthMyRecipesIndexRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/recipe-image': typeof ApiRecipeImageRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/recipes/': typeof RecipesIndexRoute
  '/_auth/my-recipes/new': typeof AuthMyRecipesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/_auth/my-recipes/': typeof AuthMyRecipesIndexRoute
  '/recipes/$recipeId/': typeof RecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/api/recipe-image'
    | '/profile/$username'
    | '/recipes/'
    | '/my-recipes/new'
    | '/api/auth/$'
    | '/recipes/$recipeId/edit'
    | '/my-recipes/'
    | '/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/api/recipe-image'
    | '/profile/$username'
    | '/recipes'
    | '/my-recipes/new'
    | '/api/auth/$'
    | '/recipes/$recipeId/edit'
    | '/my-recipes'
    | '/recipes/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/sign-in'
    | '/sign-up'
    | '/api/recipe-image'
    | '/profile/$username'
    | '/recipes/'
    | '/_auth/my-recipes/new'
    | '/api/auth/$'
    | '/recipes/$recipeId/edit'
    | '/_auth/my-recipes/'
    | '/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiRecipeImageRoute: typeof ApiRecipeImageRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  RecipesRecipeIdEditRoute: typeof RecipesRecipeIdEditRoute
  RecipesRecipeIdIndexRoute: typeof RecipesRecipeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipe-image': {
      id: '/api/recipe-image'
      path: '/api/recipe-image'
      fullPath: '/api/recipe-image'
      preLoaderRoute: typeof ApiRecipeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId/': {
      id: '/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId/'
      preLoaderRoute: typeof RecipesRecipeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/my-recipes/': {
      id: '/_auth/my-recipes/'
      path: '/my-recipes'
      fullPath: '/my-recipes/'
      preLoaderRoute: typeof AuthMyRecipesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/recipes/$recipeId/edit': {
      id: '/recipes/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof RecipesRecipeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/my-recipes/new': {
      id: '/_auth/my-recipes/new'
      path: '/my-recipes/new'
      fullPath: '/my-recipes/new'
      preLoaderRoute: typeof AuthMyRecipesNewRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthMyRecipesNewRoute: typeof AuthMyRecipesNewRoute
  AuthMyRecipesIndexRoute: typeof AuthMyRecipesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMyRecipesNewRoute: AuthMyRecipesNewRoute,
  AuthMyRecipesIndexRoute: AuthMyRecipesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiRecipeImageRoute: ApiRecipeImageRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  RecipesRecipeIdEditRoute: RecipesRecipeIdEditRoute,
  RecipesRecipeIdIndexRoute: RecipesRecipeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
